export const authActionTypes = {
  TOGGLE_EXPANDED_STATE: "TOGGLE_EXPANDED_STATE",
  TOGGLE_LOGIN_STATE: "TOGGLE_LOGIN_STATE",
  AUTH_START: "AUTH_START",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILED: "SIGNUP_FAILED",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
};
