export const userActionTypes = {
  TOGGLE_NEW_TODO_FORM: "TOGGLE_NEW_TODO_FORM",
  FETCH_TODOS_START: "FETCH_TODOS_START",
  FETCH_TODOS_SUCCESS: "FETCH_TODOS_SUCCESS",
  ADD_TODO_START: "ADD_TODO_START",
  ADD_TODO_SUCCESS: "ADD_TODO_SUCCESS",
  UPDATE_TODO: "UPDATE_TODO",
  DELETE_TODO_START: "DELETE_TODO_START",
  DELETE_TODO_SUCCESS: "DELETE_TODO_SUCCESS",
  CLEAR_TODOS: "CLEAR_TODOS",
};
